"""
Experiment 2: hard-negative weighted training. Uses the CONFIRMED baseline OOF (weight=1,
same 5-fold split as production) as a fold-safe hardness diagnostic: for label=0 rows,
OOF probability was generated by a model that never saw that row's own label, so it's a
valid hardness signal to use when constructing sample weights for a SEPARATE retraining
pass on the same folds. base weight = 1 everywhere (per Experiment 1's GO result); hard
negatives get an extra multiplier.
"""
import io, os, json, time
import numpy as np
import dill

d = os.path.dirname(os.path.abspath(__file__))
t0 = time.time()
with open(os.path.join(d, '_cache.dill'), 'rb') as f:
    ns = dill.load(f)
nb = json.load(io.open(os.path.join(d, 'ifest2026_dac_v13_final.ipynb'), encoding='utf-8'))
cells = [''.join(c['source']) for c in nb['cells'] if c['cell_type'] == 'code']
ns['Ftr'] = ns['_Ftr_base'].copy(); ns['Fte'] = ns['_Fte_base'].copy()
exec(compile(cells[7], os.path.join(d, '_fast_claim.py'), 'exec'), ns)
print(f"features ready in {time.time()-t0:.1f}s")

from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import f1_score
import catboost as cb

train = ns['train']; Ftr = ns['Ftr']; y = ns['y']; ALL_A_FEATS = ns['ALL_A_FEATS']; SEED = ns['SEED']
groups = train['ch'].values
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SEED)
folds = list(sgkf.split(train, y, groups))
Xa = Ftr[ALL_A_FEATS].values
cold_mask = train['ch'].map(train['ch'].value_counts()).eq(1).values
cy_all = y[cold_mask]

def macro_best(oof):
    cp = oof[cold_mask]
    best = (0.5, -1)
    for t in np.arange(0.02, 0.98, 0.01):
        mac = f1_score(cy_all, (cp >= t).astype(int), average='macro')
        if mac > best[1]: best = (t, mac)
    return best

# Step 1: baseline OOF (weight=1, unweighted) -- the fold-safe hardness diagnostic.
t1 = time.time()
oof_base = np.zeros(len(y))
for a, b in folds:
    m = cb.CatBoostClassifier(iterations=800, depth=6, learning_rate=0.03,
                               class_weights=[1, 1], random_seed=SEED, verbose=False)
    m.fit(Xa[a], y[a])
    oof_base[b] = m.predict_proba(Xa[b])[:, 1]
thr0, mac0 = macro_best(oof_base)
print(f"baseline (weight=1, unweighted): Macro F1 = {mac0:.4f} @ thr={thr0:.3f}  ({time.time()-t1:.1f}s)")

# Step 2: build hard-negative sample weights from oof_base (label=0 rows only; label=1 rows
# always weight=1, per Experiment 1's finding that positives don't need reweighting).
def hardness_weights(oof, y_, easy_hard_cut, very_hard_cut, hard_mult, very_hard_mult):
    w = np.ones(len(y_))
    neg_mask = (y_ == 0)
    hard = neg_mask & (oof >= easy_hard_cut) & (oof < very_hard_cut)
    very_hard = neg_mask & (oof >= very_hard_cut)
    w[hard] = hard_mult
    w[very_hard] = very_hard_mult
    return w

configs = [
    dict(name='1.5x/2.0x @ .7/.9', easy_hard_cut=0.7, very_hard_cut=0.9, hard_mult=1.5, very_hard_mult=2.0),
    dict(name='1.3x/1.6x @ .7/.9', easy_hard_cut=0.7, very_hard_cut=0.9, hard_mult=1.3, very_hard_mult=1.6),
    dict(name='2.0x/3.0x @ .8/.95', easy_hard_cut=0.8, very_hard_cut=0.95, hard_mult=2.0, very_hard_mult=3.0),
]

for cfg in configs:
    t1 = time.time()
    sw = hardness_weights(oof_base, y, cfg['easy_hard_cut'], cfg['very_hard_cut'], cfg['hard_mult'], cfg['very_hard_mult'])
    oof = np.zeros(len(y))
    for a, b in folds:
        m = cb.CatBoostClassifier(iterations=800, depth=6, learning_rate=0.03,
                                   random_seed=SEED, verbose=False)
        m.fit(Xa[a], y[a], sample_weight=sw[a])
        oof[b] = m.predict_proba(Xa[b])[:, 1]
    thr, mac = macro_best(oof)
    print(f"{cfg['name']:22s}: Macro F1 = {mac:.4f} @ thr={thr:.3f}  (n_hard={int(((y==0)&(oof_base>=cfg['easy_hard_cut'])).sum())})  ({time.time()-t1:.1f}s)")

print(f"\n(reference: Experiment 1 baseline weight=1 unweighted = {mac0:.4f})")
print(f"TOTAL wall time: {time.time()-t0:.1f}s")
