import nbformat as nbf, textwrap

nb = nbf.v4.new_notebook(); cells = []
def md(s): cells.append(nbf.v4.new_markdown_cell(textwrap.dedent(s).strip()))
def code(s): cells.append(nbf.v4.new_code_cell(textwrap.dedent(s).strip()))

md("""
# Penyisihan IFEST 2026 DAC — V8: Rule-Constrained Compliant System

## Rules compliance (this notebook uses NO pre-trained models)

Competition rules state:
- *"Penggunaan model pre-trained, seperti IndoBERT, BERT, XLM-R, FastText pre-trained, dan
  model sejenis tidak diperbolehkan."*
- *"Penggunaan VLM, LLM, generative AI, dan API model untuk menghasilkan prediksi, label,
  embedding, atau fitur tidak diperbolehkan."*
- *"TF-IDF, CountVectorizer, BM25, serta embedding yang dilatih dari awal menggunakan data
  kompetisi diperbolehkan."*

Everything below is built **only** from: TF-IDF / CountVectorizer, a from-scratch BM25
implementation, LSA embeddings fit on the competition corpus itself, hand-written
features, and classical classifiers (linear + gradient boosting). No pre-trained weights
are downloaded or used anywhere, and no external data is required — the kernel can run
with internet disabled.

## What the data analysis established

1. **Negatives are generated by swapping one proper noun in a true headline.** Of the
   same-body title pairs, 529/1097 differ by exactly one token and 95% of swapped tokens
   are proper nouns (`DKI`->`Jabar`, `Karawang`->`Bekasi`, `Jokowi`->`Prabowo`); 96% of
   the substitutes come from the corpus's own entity pool. So the task is fine-grained
   entity verification, and the features below target that directly rather than topical
   similarity.
2. **Validation must be split by regime.** A grouped split contains zero rows of the
   regime where most negatives live:

   | regime | share | class-0 rate |
   |---|---|---|
   | A cold-start (body unseen) | 67.4% | 6.0% |
   | B same body, new title | 10.0% | **60.4%** |
   | C exact (title,body) pair seen | 22.6% | known from train |

3. **Regime B is near-deterministic**, which follows from the construction (one true
   headline per article + tampered variants):
   `P(label=0 | body seen, train already shows a label=1 title, this title is new) = 0.977`

## Architecture

```
                  (title, body)
                        |
        +---------------+----------------+
        |               |                |
   BM25 retrieval   TF-IDF word/char   entity + number +
   (from scratch)   + LSA (from scratch) negation analysis
        |               |                |
        +---------------+----------------+
                        v
              ~40 consistency features
                        |
            +-----------+-----------+
            v                       v
     LinearSVC / LogReg        LightGBM
     on sparse TF-IDF          on dense features
            |                       |
            +-----------+-----------+
                        v
                 blended probability
                        |
              threshold (global objective)
                        |
                        v
        rule layer (config flag) -> final label
```

The rule layer is **one component, not the system** — the model is trained and blended to
carry the cold-start rows (63.6% of test) on its own, and `USE_RULES` can be switched off
without touching anything else if the organizers rule it out.
""")

md("## 1. Environment (no pre-trained downloads, no internet required)")

code("""
import os, re, time, json, math, hashlib, unicodedata, warnings, random, string as _s
warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
from collections import Counter, defaultdict

SEED=42; random.seed(SEED); np.random.seed(SEED)
import sklearn; print("sklearn", sklearn.__version__)
try:
    import lightgbm as lgb; HAS_LGB=True; print("lightgbm", lgb.__version__)
except Exception as e:
    HAS_LGB=False; print("lightgbm unavailable -> falling back to sklearn GBDT:", e)

TIMINGS={}
class Timer:
    def __init__(s,n): s.n=n
    def __enter__(s): s.t=time.time(); return s
    def __exit__(s,*a):
        d=time.time()-s.t; TIMINGS[s.n]=TIMINGS.get(s.n,0)+d; print(f"[TIMER] {s.n}: {d:.1f}s")
RUN_T0=time.time()

CONFIG=dict(
    seed=SEED, n_folds=5, val_frac=0.15,
    chunk_words=50, chunk_stride=25,
    bm25_k1=1.5, bm25_b=0.75, top_k=5,
    lsa_dim=160, tfidf_word_max=60000, tfidf_char_max=40000,
    entity_min_count=8, entity_min_purity=0.95, entity_max_title_df=0.02,
    USE_RULES=True,           # flip to False if the organizers disallow the lookup layer
    threshold_grid=[round(x,3) for x in np.arange(0.05,0.96,0.025)],
    test_mix={'A_cold':0.636,'C_exact':0.257,'B_has_pos':0.060,'B_no_pos':0.046},
)
print(json.dumps(CONFIG,indent=2,default=str))
""")

md("## 2. Load data + rule-layer lookups")

code("""
with Timer("load"):
    F={}
    for r,_,fs in os.walk('/kaggle/input'):
        for f in fs:
            if f in ('train.csv','test.csv','sample_submission.csv'): F.setdefault(f,os.path.join(r,f))
    assert len(F)==3, F
    train=pd.read_csv(F['train.csv']); test=pd.read_csv(F['test.csv']); sample_sub=pd.read_csv(F['sample_submission.csv'])

def nh(x):
    x=unicodedata.normalize('NFKC',str(x)).lower(); return re.sub(r'\\s+',' ',x).strip()
for d in (train,test):
    d['ch']=d['content'].apply(lambda s: hashlib.md5(nh(s).encode()).hexdigest())
    d['th']=d['title'].apply(lambda s: hashlib.md5(nh(s).encode()).hexdigest())
print("train",train.shape,"test",test.shape,"| class0",round((train.label==0).mean(),4))

def build_lookups(df):
    pair={}; byc=defaultdict(list)
    for th,ch,lb in zip(df['th'],df['ch'],df['label']):
        pair[(th,ch)]=lb; byc[ch].append((th,lb))
    return pair,byc

def rule_predict(df,pair,byc):
    reg=[];lab=[]
    for th,ch in zip(df['th'],df['ch']):
        if (th,ch) in pair: reg.append('C_exact'); lab.append(pair[(th,ch)])
        elif ch in byc:
            if any(l==1 for _,l in byc[ch]): reg.append('B_has_pos'); lab.append(0)
            else: reg.append('B_no_pos'); lab.append(1)
        else: reg.append('A_cold'); lab.append(None)
    return np.array(reg), lab
""")

md("""
## 3. Regime validation of the rule layer

Verified on a **random** split, because its regime mix (67/10/23) matches test (64/11/26);
a grouped split cannot contain regime B at all.
""")

code("""
from sklearn.metrics import f1_score, confusion_matrix
with Timer("rule_validation"):
    rs=np.random.RandomState(SEED); perm=rs.permutation(len(train)); cut=int(0.85*len(train))
    rtr,rva=perm[:cut],perm[cut:]
    p_,b_=build_lookups(train.iloc[rtr])
    REG_VA,RULE_VA=rule_predict(train.iloc[rva],p_,b_)
    Y_VA=train['label'].iloc[rva].values
    for r in ['A_cold','B_has_pos','B_no_pos','C_exact']:
        m=REG_VA==r
        if m.sum():
            acc=np.mean([RULE_VA[i]==Y_VA[i] for i in np.where(m)[0]]) if r!='A_cold' else float('nan')
            print(f"  {r:10s} n={m.sum():5d} ({m.mean()*100:5.1f}%)  class0={np.mean(Y_VA[m]==0):.3f}  rule_acc={acc:.4f}")
    only=np.array([1 if l is None else l for l in RULE_VA])
    RULES_ONLY=f1_score(Y_VA,only,average='macro')
    print(f"\\nrules only (cold-start all 1): Macro F1 = {RULES_ONLY:.4f}")
""")

md("## 4. Model split (grouped — the model's job is cold-start rows)")

code("""
from sklearn.model_selection import StratifiedGroupKFold
with Timer("split"):
    y=train['label'].values; groups=train['ch'].values
    sgkf=StratifiedGroupKFold(n_splits=CONFIG['n_folds'],shuffle=True,random_state=SEED)
    folds=list(sgkf.split(train,y,groups))
    for i,(a,b) in enumerate(folds):
        assert not (set(groups[a])&set(groups[b]))
        print(f"  fold{i}: train {len(a)} val {len(b)} class0 {np.mean(y[b]==0):.3f}")
""")

md("## 5. Cleaning + entity mining (derived from competition data only)")

code("""
URL=re.compile(r'https?://\\S+|www\\.\\S+'); HTML=re.compile(r'<[^>]+>'); WS=re.compile(r'\\s+')
def clean(s):
    s=unicodedata.normalize('NFKC',str(s)); s=HTML.sub(' ',s); s=URL.sub(' ',s)
    return WS.sub(' ',s).strip()
with Timer("clean"):
    for d in (train,test):
        d['T']=d['title'].apply(clean); d['C']=d['content'].apply(clean)

NUM=re.compile(r'\\d+[.,]?\\d*\\s*%?'); YEAR=re.compile(r'\\b(?:19|20)\\d{2}\\b')
NEG=['tidak','bukan','belum','tanpa','gagal','ditolak','membantah','bantah','sangkal','menyangkal','menolak']

with Timer("entity_mining"):
    up,lo=Counter(),Counter()
    for t in train['C']:
        for w in t.split():
            c=w.strip(_s.punctuation)
            if not c.isalpha() or len(c)<3: continue
            if c[:1].isupper(): up[c]+=1
            else: lo[c.capitalize()]+=1
    pur={w:up[w]/(up[w]+lo.get(w,0)) for w in up if up[w]>=CONFIG['entity_min_count']}
    tdf=Counter()
    for t in train['T']:
        for w in set(t.split()): tdf[w]+=1
    ENT={w for w,p in pur.items() if p>=CONFIG['entity_min_purity'] and tdf.get(w,0)/len(train)<CONFIG['entity_max_title_df']}
    print("entity pool:",len(ENT))
    for w in ['DKI','Jabar','Jokowi','Tidak','Corona']:
        if w in pur: print(f"   {w:8s} purity={pur[w]:.2f} in_pool={w in ENT}")
""")

md("## 6. Chunking + from-scratch BM25 (explicitly permitted)")

code("""
def chunks_of(s,w=CONFIG['chunk_words'],st=CONFIG['chunk_stride']):
    ws=s.split()
    if not ws: return ['']
    if len(ws)<=w: return [' '.join(ws)]
    out=[]
    for i in range(0,len(ws),st):
        c=ws[i:i+w]
        if not c: break
        out.append(' '.join(c))
        if i+w>=len(ws): break
    return out

def toks(s): return re.findall(r"[\\w']+", s.lower())

with Timer("chunk_index"):
    allpairs=pd.concat([train[['ch','C']],test[['ch','C']]],ignore_index=True).drop_duplicates('ch')
    chunk_txt={};
    for h,c in zip(allpairs['ch'],allpairs['C']): chunk_txt[h]=chunks_of(c)
    # global chunk statistics for BM25
    df_cnt=Counter(); total_len=0; n_chunks=0
    chunk_tf={}
    for h,cs in chunk_txt.items():
        tfs=[]
        for c in cs:
            tk=toks(c); tf=Counter(tk); tfs.append((tf,len(tk)))
            total_len+=len(tk); n_chunks+=1
            for t in tf: df_cnt[t]+=1
        chunk_tf[h]=tfs
    AVGDL=total_len/max(n_chunks,1)
    IDF={t: math.log(1+(n_chunks-c+0.5)/(c+0.5)) for t,c in df_cnt.items()}
    print(f"articles {len(chunk_txt)}  chunks {n_chunks}  avg chunk len {AVGDL:.1f}  vocab {len(IDF)}")

k1,b=CONFIG['bm25_k1'],CONFIG['bm25_b']
def bm25_scores(title, ch):
    q=toks(title); out=[]
    for tf,L in chunk_tf[ch]:
        s=0.0
        for t in q:
            f=tf.get(t,0)
            if f: s+=IDF.get(t,0.0)*(f*(k1+1))/(f+k1*(1-b+b*L/AVGDL))
        out.append(s)
    return np.array(out) if out else np.array([0.0])
""")

md("## 7. LSA embeddings trained from scratch on the competition corpus")

code("""
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize

with Timer("lsa"):
    corpus = pd.concat([train['T'],train['C'],test['T'],test['C']]).tolist()
    lsa_tfidf=TfidfVectorizer(ngram_range=(1,1),min_df=3,sublinear_tf=True,max_features=80000)
    Xc=lsa_tfidf.fit_transform(corpus)
    svd=TruncatedSVD(n_components=CONFIG['lsa_dim'],random_state=SEED)
    svd.fit(Xc)
    def embed(texts): return normalize(svd.transform(lsa_tfidf.transform(texts)))
    for d in (train,test):
        d_t=embed(d['T'].tolist()); d_c=embed(d['C'].tolist())
        d['lsa_cos']=np.sum(d_t*d_c,axis=1)
    print("explained variance:",round(float(svd.explained_variance_ratio_.sum()),4))
    print("lsa_cos by label:\\n",train.groupby('label')['lsa_cos'].mean().round(4))
""")

md("""
## 8. Consistency features

Targeted at the entity-swap mechanism rather than generic similarity. The sharpest single
feature is `n_title_ent_missing` (measured: 38% of negatives vs 9.8% of positives), and
`swap_signature` looks for a missing title entity whose *neighbouring* title words are
present in the body — the fingerprint of a substitution.
""")

code("""
IDF_TITLE = None
def build_features(df):
    rows=[]
    for T,C,ch,lsa in zip(df['T'],df['C'],df['ch'],df['lsa_cos']):
        tw=toks(T); cw=toks(C)
        tset,cset=set(tw),set(cw)
        craw={w.strip(_s.punctuation) for w in C.split()}
        inter=tset&cset; union=tset|cset
        tb=set(zip(tw,tw[1:])); cb=set(zip(cw,cw[1:]))
        tents=[w for w in T.split() if w in ENT]
        miss=[w for w in tents if w not in craw]
        # swap signature: entity missing while its title-neighbours ARE in the body
        sig=0
        Ttok=T.split()
        for i,w in enumerate(Ttok):
            if w in ENT and w not in craw:
                nb=[Ttok[j] for j in (i-1,i+1) if 0<=j<len(Ttok)]
                nb=[x for x in nb if x.lower() not in ('dan','di','ke','yang')]
                if nb and all(x.strip(_s.punctuation) in craw for x in nb): sig+=1
        tn,cn=set(NUM.findall(T)),set(NUM.findall(C))
        ty,cy=set(YEAR.findall(T)),set(YEAR.findall(C))
        bm=bm25_scores(T,ch); order=np.argsort(-bm)
        topk=bm[order[:CONFIG['top_k']]]
        # idf-weighted coverage: rare title terms are what get swapped
        num_=sum(IDF.get(t,0.0) for t in tset&cset); den_=sum(IDF.get(t,0.0) for t in tset)
        rows.append(dict(
            n_shared=len(inter), jaccard=len(inter)/max(len(union),1),
            dice=2*len(inter)/max(len(tset)+len(cset),1),
            title_cov=len(inter)/max(len(tset),1), content_cov=len(inter)/max(len(cset),1),
            bigram_ov=len(tb&cb)/max(len(tb|cb),1),
            idf_title_cov=num_/max(den_,1e-6),
            n_title_ent=len(tents), n_title_ent_missing=len(miss),
            frac_title_ent_missing=len(miss)/max(len(tents),1),
            any_title_ent_missing=float(len(miss)>0), swap_signature=float(sig>0), n_swap_sig=sig,
            n_num_title=len(tn), n_num_missing=len(tn-cn),
            num_overlap=len(tn&cn)/max(len(tn),1) if tn else 1.0,
            num_mismatch=float(bool(tn) and not (tn&cn)),
            n_year_title=len(ty), year_missing=float(bool(ty) and not (ty&cy)),
            neg_title=float(any(w in tset for w in NEG)), neg_body=float(any(w in cset for w in NEG)),
            neg_mismatch=float(any(w in tset for w in NEG)!=any(w in cset for w in NEG)),
            bm25_max=float(bm.max()), bm25_mean=float(bm.mean()),
            bm25_top=float(topk.mean()), bm25_std=float(bm.std()),
            bm25_argmax_pos=float(order[0]/max(len(bm)-1,1)), n_chunks=len(bm),
            lsa_cos=float(lsa),
            len_title=len(tw), len_content=len(cw), len_ratio=len(tw)/max(len(cw),1),
        ))
    return pd.DataFrame(rows,index=df.index)

with Timer("features"):
    Ftr=build_features(train); Fte=build_features(test)
    FEATS=list(Ftr.columns)
print(f"{len(FEATS)} features")
print(pd.concat([Ftr[['n_title_ent_missing','swap_signature','idf_title_cov','bm25_max','lsa_cos','num_mismatch']],
                 train['label']],axis=1).groupby('label').mean().round(4).T)
""")

md("## 9. Models — sparse TF-IDF linear + LightGBM on dense features, 5-fold grouped OOF")

code("""
from sklearn.linear_model import LogisticRegression
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC
import scipy.sparse as sp

def fit_sparse(tr_i, va_i, te=False):
    tv=TfidfVectorizer(ngram_range=(1,2),min_df=2,sublinear_tf=True,max_features=20000,strip_accents='unicode')
    cv_=TfidfVectorizer(ngram_range=(1,2),min_df=2,sublinear_tf=True,max_features=CONFIG['tfidf_word_max'],strip_accents='unicode')
    ct=TfidfVectorizer(analyzer='char',ngram_range=(3,5),min_df=3,sublinear_tf=True,max_features=CONFIG['tfidf_char_max'])
    A=tv.fit_transform(train['T'].iloc[tr_i]); B=cv_.fit_transform(train['C'].iloc[tr_i]); Cc=ct.fit_transform(train['T'].iloc[tr_i])
    Xtr=sp.hstack([A,B,Cc]).tocsr()
    def tf(df): return sp.hstack([tv.transform(df['T']),cv_.transform(df['C']),ct.transform(df['T'])]).tocsr()
    clf=LogisticRegression(max_iter=3000,class_weight='balanced',C=2.0,random_state=SEED)
    clf.fit(Xtr,y[tr_i])
    out_va=clf.predict_proba(tf(train.iloc[va_i]))[:,1]
    out_te=clf.predict_proba(tf(test))[:,1] if te else None
    return out_va,out_te

def fit_dense(tr_i,va_i,te=False):
    Xtr=Ftr.iloc[tr_i].values; Xva=Ftr.iloc[va_i].values
    if HAS_LGB:
        m=lgb.LGBMClassifier(n_estimators=600,learning_rate=0.05,num_leaves=31,
                              subsample=0.9,colsample_bytree=0.8,class_weight='balanced',
                              random_state=SEED,verbose=-1)
    else:
        from sklearn.ensemble import HistGradientBoostingClassifier
        m=HistGradientBoostingClassifier(max_iter=500,learning_rate=0.05,random_state=SEED)
    m.fit(Xtr,y[tr_i])
    return m.predict_proba(Xva)[:,1], (m.predict_proba(Fte.values)[:,1] if te else None), m

with Timer("cv"):
    oof_s=np.zeros(len(train)); oof_d=np.zeros(len(train))
    for i,(a,b) in enumerate(folds):
        s,_=fit_sparse(a,b); d,_,m=fit_dense(a,b)
        oof_s[b]=s; oof_d[b]=d
        print(f"  fold{i} sparse={f1_score(y[b],(s>=0.5).astype(int),average='macro'):.4f} "
              f"dense={f1_score(y[b],(d>=0.5).astype(int),average='macro'):.4f}")
print("OOF sparse macroF1@0.5:",round(f1_score(y,(oof_s>=.5).astype(int),average='macro'),4))
print("OOF dense  macroF1@0.5:",round(f1_score(y,(oof_d>=.5).astype(int),average='macro'),4))
if HAS_LGB:
    imp=pd.Series(m.feature_importances_,index=FEATS).sort_values(ascending=False)
    print("\\ntop features:\\n",imp.head(15))
""")

md("## 10. Blend + threshold under the test regime mixture")

code("""
with Timer("blend_threshold"):
    best=(None,-1)
    for wgt in np.arange(0,1.01,0.05):
        p=wgt*oof_s+(1-wgt)*oof_d
        sc=max(f1_score(y,(p>=t).astype(int),average='macro') for t in CONFIG['threshold_grid'])
        if sc>best[1]: best=(wgt,sc)
    W=best[0]; oof=W*oof_s+(1-W)*oof_d
    print(f"blend weight (sparse)={W:.2f}  cold-style OOF macroF1={best[1]:.4f}")

    # global objective: rules supply most negatives, so tune the model for recall on the rest
    rule_rows=[(r,Y_VA[i],RULE_VA[i]) for i,r in enumerate(REG_VA) if RULE_VA[i] is not None]
    rdf=pd.DataFrame(rule_rows,columns=['regime','y','pred'])
    # The model only ever sees rows the rules cannot decide. Rows whose body repeats in
    # train become regime B/C at inference and are answered by rules, so including them
    # here (they are ~60% class-0 and the model is bad at them) mis-specifies the mixture
    # and drags the threshold to a bad operating point. The true cold-start analogue is
    # rows whose body occurs exactly once in train.
    _cnt=train['ch'].value_counts()
    cold_mask=train['ch'].map(_cnt).eq(1).values
    cold_oof=oof[cold_mask]; cold_y=y[cold_mask]
    print(f"cold-start analogue rows: {cold_mask.sum()} (class0 {np.mean(cold_y==0):.3f}) "
          f"vs all-train class0 {np.mean(y==0):.3f}")
    n_cold=cold_mask.sum(); total=int(n_cold/CONFIG['test_mix']['A_cold']); rs2=np.random.RandomState(SEED)
    parts=[]
    for r in ['C_exact','B_has_pos','B_no_pos']:
        pool=rdf[rdf.regime==r]; k=int(round(CONFIG['test_mix'][r]*total))
        if len(pool) and k: parts.append(pool.iloc[rs2.choice(len(pool),k,replace=len(pool)<k)])
    rp=pd.concat(parts,ignore_index=True) if parts else pd.DataFrame(columns=['regime','y','pred'])

    rows=[]
    for t in CONFIG['threshold_grid']:
        cp=(cold_oof>=t).astype(int)
        if CONFIG['USE_RULES'] and len(rp):
            ya=np.concatenate([cold_y,rp['y'].values]); pa=np.concatenate([cp,rp['pred'].values])
        else:
            ya,pa=cold_y,cp
        rows.append(dict(threshold=t,global_f1=f1_score(ya,pa,average='macro'),
                         cold_f1=f1_score(cold_y,cp,average='macro'),
                         rec0=((cp==0)&(cold_y==0)).sum()/max((cold_y==0).sum(),1),
                         prec0=((cp==0)&(cold_y==0)).sum()/max((cp==0).sum(),1)))
    tdf=pd.DataFrame(rows)
    THR=float(tdf.loc[tdf.global_f1.idxmax(),'threshold']); GLOBAL=float(tdf.global_f1.max())
    print(tdf.iloc[::4].round(4).to_string(index=False))
    # what would rules-only score under this same mixture? (model must beat this to earn its place)
    base_pred=np.concatenate([np.ones(len(cold_y),int),rp['pred'].values]) if len(rp) else np.ones(len(cold_y),int)
    base_y=np.concatenate([cold_y,rp['y'].values]) if len(rp) else cold_y
    RULES_ONLY_MIX=f1_score(base_y,base_pred,average='macro')
print(f"chosen threshold {THR} -> simulated global Macro F1 {GLOBAL:.4f}")
print(f"  rules-only under the same mixture: {RULES_ONLY_MIX:.4f}  -> model contributes {GLOBAL-RULES_ONLY_MIX:+.4f}")
""")

md("## 11. Refit on all data, predict test, apply rule layer, submit")

code("""
with Timer("final"):
    idx=np.arange(len(train))
    s_va,s_te=fit_sparse(idx,idx[:1],te=True)
    d_va,d_te,mfull=fit_dense(idx,idx[:1],te=True)
    tp=W*s_te+(1-W)*d_te
    model_pred=(tp>=THR).astype(int)
    print("model positive rate on test:",round(model_pred.mean(),4))

with Timer("submit"):
    pair_all,byc_all=build_lookups(train)
    reg_t,rule_t=rule_predict(test,pair_all,byc_all)
    if CONFIG['USE_RULES']:
        final=np.array([model_pred[i] if rule_t[i] is None else rule_t[i] for i in range(len(test))])
    else:
        final=model_pred
    for r in ['A_cold','B_has_pos','B_no_pos','C_exact']:
        m=reg_t==r
        if m.sum(): print(f"  {r:10s} n={m.sum():5d}  positive rate={final[m].mean():.3f}")
    ov=sum(1 for i in range(len(test)) if rule_t[i] is not None and rule_t[i]!=model_pred[i])
    print("rows where a rule overrode the model:",ov)

    sub=pd.DataFrame({'id':test['id'],'label':final.astype(int)}).set_index('id').loc[test['id']].reset_index()
    assert sub.shape[0]==len(test) and set(sub['id'])==set(sample_sub['id'])
    assert set(sub['label'].unique())<={0,1} and list(sub.columns)==['id','label']
    sub.to_csv('/kaggle/working/submission.csv',index=False)
    # also emit a rules-off variant so the compliant fallback is ready without a rerun
    sub_nr=pd.DataFrame({'id':test['id'],'label':model_pred.astype(int)})
    sub_nr.to_csv('/kaggle/working/submission_model_only.csv',index=False)
print(sub['label'].value_counts(normalize=True))
""")

code("""
T=time.time()-RUN_T0
print("="*58)
print("V8 — fully rules-compliant (no pre-trained models anywhere)")
print(f"OOF sparse/dense/blend : {f1_score(y,(oof_s>=.5).astype(int),average='macro'):.4f} / "
      f"{f1_score(y,(oof_d>=.5).astype(int),average='macro'):.4f} / {best[1]:.4f} (w={W:.2f})")
print(f"rules-only reference   : {RULES_ONLY:.4f}")
print(f"simulated global F1    : {GLOBAL:.4f} @ threshold {THR} (rules-only {RULES_ONLY_MIX:.4f}, model {GLOBAL-RULES_ONLY_MIX:+.4f})")
print(f"USE_RULES              : {CONFIG['USE_RULES']}")
print(f"total runtime          : {T/60:.1f} min  (CPU only)")
print("="*58)
for k,v in sorted(TIMINGS.items(),key=lambda kv:-kv[1]): print(f"  {k}: {v:.1f}s")
""")

nb['cells']=cells
nb['metadata']['kernelspec']={'display_name':'Python 3','language':'python','name':'python3'}
nb['metadata']['language_info']={'name':'python','version':'3.11'}
with open('ifest2026_dac_v8_legal.ipynb','w',encoding='utf-8') as f: nbf.write(nb,f)
print("Notebook written.")
